### ISSUE TITLE
Presence of hard association in the compactness portion of loss function

### ISSUE THREAD

**Issue by ghost** [NVlabs/ssn_superpixels#16]
Hi, I wanted to ask you about a technicality in the compactness portion of the loss function.
The compactness loss uses inverse mapping onto the pixel representation using the _hard associations H_, instead of the soft association Q. My question is how is the non-differentiability of the hard association in the loss function resolved - there appears to be no reference to any form of Monte Carlo optimization (e.g. REINFORCE) to circumvent the non-differentiability issue (the very presence of hard association in the loss function also appears to go against the founding principles of differentiable SLIC).

I would really appreciate hearing your thoughts on this.
Thanks in advance :)

**Comment by varunjampani** [comment]
Good question. We tried compactness loss with both soft and hard associations. Empirically, it worked better with hard associations. It it probably because the network can learn to cheat if we use soft-associations by producing superpixels that are not compact but has soft-associations that minimize this loss.

To be more precise, we use both soft and hard associations while computing this loss function. We first convert pixel-positions into superpixel-positions using soft associations. Then, we map back superpixel-positions into pixel-positions using hard-associations. The gradients will still flow through superpixel-positions that are computed using soft associations. But, gradients do not flow through reconstructed pixel-positions.
