### ISSUE TITLE
where to install Caffe inside "ssn_superpixels"

### ISSUE THREAD

**Issue by ghost** [NVlabs/ssn_superpixels#21]
Hi, I have a question about how step 4 of the README.md file.

Step 4 reads, “install caffe following the installations instructions. In the ssn_superpixels/lib directory …”, after which the “Note” reads “if you install Caffe in some other folder, update CAFFEDIR in config.py accordingly”.

In the linked “instructions” there are multiple ways of installing caffe - ubuntu standard installation, docker etc, the last of which downloads and installs Caffe from source. How should Caffe be ideally installed and where should it be installed to? I’m asking this because it’s not very clear what you mean by “if you install Caffe in some other folder ...”; does this imply that when downloading Caffe from source, the “git clone https://github.com/BVLC/caffe.git” command should be performed inside the “ssn_superpixels/lib” directory? 

Thanks in advance

**Comment by yuzhegao** [comment]
In step 2, when you use the command "git clone https://github.com/varunjampani/video_prop_networks.git",you have downloaded the caffe source in directory " ssn_superpixels/lib/video_prop_networks/lib/caffe". Maybe the author recommend to use the caffe of  "video_prop_networks" repository because this ssn should use some custom layer in this caffe , so just follow the README and install caffe inside ''ssn_superpixels'

**Comment by varunjampani** [comment]
By Caffe installation, we mean installing from source. As mentioned in the above comment, it is best to use caffe from 'video_prop_networks' as this work uses some custom layers from that. You can also install latest caffe from BVLC and patch all the custom layers from video_prop_networks and additional layers used in this work.
